[[keyboard.bindings]]
key = "C"
mods = "Alt"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
action = "Paste"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"


[window]
dimensions = { columns = 130, lines = 35 }
